FROM quay.io/redhat-user-workloads/ose-osc-tenant/trustee/trustee:0a91f088edf34efecabb9263605eeb736f4186d4

# Install runtime dependencies from Intel repo.
WORKDIR /root
RUN curl -O https://download.01.org/intel-sgx/sgx-linux/2.24/distro/centos-stream9/sgx_rpm_local_repo.tgz && \
echo "91b11cee5d1f6b65a9a5fb31b8b8168da98af2af685abda34c5d709f80cd7704 sgx_rpm_local_repo.tgz" | sha256sum --check && \
tar -xaf sgx_rpm_local_repo.tgz && \
dnf -y install --nogpgcheck --setopt=install_weak_deps=0 --repofrompath "sgx,file:///root/sgx_rpm_local_repo" \
libsgx-dcap-default-qpl libsgx-dcap-quote-verify && \
rm -rf /root/sgx_rpm_local_repo && \
dnf clean all
